name: 🚀 Jittery Core - Dart Package Release

on:
  push:
    branches: [ main ]
    paths: [ 'lib/**', 'pubspec.yaml' ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Analyze code
        run: flutter analyze

      - name: Build Package
        id: build
        run: |
          # Update version in pubspec.yaml (use year.month.patch format)
          VERSION="$(date +%Y).$(date +%m).$(date +%s | tail -c 3)"
          sed -i "s/version: .*/version: $VERSION/" pubspec.yaml
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          # Get dependencies
          flutter pub get

      - name: Publish Package
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Create release
          gh release create v${{ steps.build.outputs.version }} \
            --repo ${{ github.repository_owner }}/eapp-jittery-core \
            --title "Release v${{ steps.build.outputs.version }}" \
            --notes "Jittery Core UI Component Library" \
            --draft=false \
            --prerelease=false
          
          # Create tarball
          tar -czf eapp-jittery-core-${{ steps.build.outputs.version }}.tar.gz *
          
          # Upload package file
          gh release upload v${{ steps.build.outputs.version }} eapp-jittery-core-${{ steps.build.outputs.version }}.tar.gz \
            --repo ${{ github.repository_owner }}/eapp-jittery-core \
            --clobber
          
          # Create package index from template
          mkdir -p packages
          cp templates/dart-package-index.html packages/index.html
          sed -i "s/{{VERSION}}/${{ steps.build.outputs.version }}/g" packages/index.html
          sed -i "s/{{TIMESTAMP}}/$(date -u)/g" packages/index.html

      - name: Commit Package Index
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add packages/index.html pubspec.yaml pubspec.lock
          git commit -m "Update package index for v${{ steps.build.outputs.version }}" || echo "No changes to commit"
          git push origin main

      - name: Completion
        run: |
          echo "Jittery Core package release completed!"
          echo "Package Index: https://raw.githubusercontent.com/50gramx/eapp-jittery-core/main/packages/index.html"
          echo "Releases: https://github.com/50gramx/eapp-jittery-core/releases"
