name: Dart Package Release

on:
  push:
    branches: [ master ]
    paths: [ 'lib/**', 'pubspec.yaml' ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.1.2'

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Analyze code
        run: dart analyze

      - name: Build Package
        id: build
        run: |
          # Update version in pubspec.yaml (use year.month.patch format)
          VERSION="$(date +%Y).$(date +%m).$(date +%s | tail -c 3)"
          sed -i "s/version: .*/version: $VERSION/" pubspec.yaml
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          
          # Get dependencies
          dart pub get

      - name: Publish Package
        env:
          GH_TOKEN: ${{ secrets.PROTOBUF_TOKEN }}
        run: |
          # Create release
          gh release create v${{ steps.build.outputs.version }} \
            --repo ${{ github.repository_owner }}/eapp-jittery-core \
            --title "Release v${{ steps.build.outputs.version }}" \
            --notes "Jittery Core UI Component Library" \
            --draft=false \
            --prerelease=false
          
          # Create tarball
          tar -czf eapp-jittery-core-${{ steps.build.outputs.version }}.tar.gz *
          
          # Upload package file
          gh release upload v${{ steps.build.outputs.version }} eapp-jittery-core-${{ steps.build.outputs.version }}.tar.gz \
            --repo ${{ github.repository_owner }}/eapp-jittery-core \
            --clobber
          
          # Create package index
          mkdir -p packages
          cat > packages/index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
  <title>Dart Packages - EAPP Jittery Core</title>
  <style>
    body { 
      font-family: Arial, sans-serif; 
      margin: 40px; 
      background: #f8f9fa;
    }
    .container {
      max-width: 800px;
      margin: 0 auto;
      background: white;
      padding: 30px;
      border-radius: 10px;
      box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }
    h1 { 
      color: #2c3e50; 
      border-bottom: 3px solid #00d4aa;
      padding-bottom: 10px;
    }
    .package-list {
      background: #f8f9fa;
      padding: 20px;
      border-radius: 5px;
      margin: 20px 0;
    }
    .package-item {
      margin: 10px 0;
      padding: 10px;
      background: white;
      border-left: 4px solid #00d4aa;
      border-radius: 3px;
    }
    .package-item a {
      color: #00d4aa;
      text-decoration: none;
      font-weight: bold;
    }
    .package-item a:hover {
      text-decoration: underline;
    }
    .version-info {
      color: #7f8c8d;
      font-size: 0.9em;
      margin-top: 5px;
    }
    .install-code {
      background: #2c3e50;
      color: #ecf0f1;
      padding: 15px;
      border-radius: 5px;
      font-family: 'Courier New', monospace;
      margin: 20px 0;
    }
    .footer {
      margin-top: 30px;
      padding-top: 20px;
      border-top: 1px solid #ecf0f1;
      color: #7f8c8d;
      font-size: 0.9em;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>🎯 Dart Packages - EAPP Jittery Core</h1>
    
    <p>Framework-agnostic UI component library for Eutopia applications.</p>
    
    <div class="install-code">
      # Add to pubspec.yaml<br>
      dependencies:<br>
      &nbsp;&nbsp;eapp_jittery_core:<br>
      &nbsp;&nbsp;&nbsp;&nbsp;git:<br>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;url: https://github.com/50gramx/eapp-jittery-core.git<br>
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ref: v${{ steps.build.outputs.version }}
    </div>
    
    <div class="package-list">
      <h2>Available Packages</h2>
      <div class="package-item">
        <a href="https://github.com/50gramx/eapp-jittery-core/releases/download/v${{ steps.build.outputs.version }}/eapp-jittery-core-${{ steps.build.outputs.version }}.tar.gz">eapp-jittery-core-${{ steps.build.outputs.version }}.tar.gz</a>
        <div class="version-info">Dart package archive - ${{ steps.build.outputs.version }}</div>
      </div>
    </div>
    
    <div class="footer">
      <p><strong>Repository:</strong> <a href="https://github.com/50gramx/eapp-jittery-core">eapp-jittery-core</a></p>
      <p><strong>Generated:</strong> $(date -u)</p>
      <p><em>Auto-generated by GitHub Actions when code is updated.</em></p>
    </div>
  </div>
</body>
</html>
EOF

      - name: Commit Package Index
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update package index for v${{ steps.build.outputs.version }}" || echo "No changes to commit"
          git push origin master

      - name: Completion
        run: |
          echo "Jittery Core package release completed!"
          echo "Package Index: https://raw.githubusercontent.com/50gramx/eapp-jittery-core/master/packages/index.html"
          echo "Releases: https://github.com/50gramx/eapp-jittery-core/releases" 